---
title: "ggplot"
author: "Ronald Mego"
date: "11/21/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#gramatica por capas de ggplot2

#ggplot(data=<DATA_FRAME>)+
# <GEOM_FUNCTION>(
#                 mapping=aes(<MAPPINGS>),
#                 stat=<STAT>,
#                 position=<POSITION>
#                 )+
#   <COORDINATE_FUNCTION>()+
#   <FACET_FUNCTION>()

```{r}
library(tidyverse)
library(modeldata)
library(ggplot2)

```

```{r}
#levanto data de prueba
data("mpg")
data("diamonds")

ggplot2::mpg #base de datos de coches
view(mpg) #otra forma de verlo completo

#diccionario de datos
help(mpg) #otra forma de verlo completo

#describe la estructura de un dataset
dput(mpg)
```

UNA FORMA DE AUTOMATIZAR GRAFICOS TIPO TABLEAU CON ESQUISSE
https://www.youtube.com/watch?v=6LV_p3Zi-LM
```{r}
#OTRA FORMA DE DIBUJAR con libreria esquisse
#library(esquisse) #par ejecutar esquisser()

#demo equisser
#esquisser()
```

OTRA FORMA DE AUTOMATIZAR GRAFICOS DE SERIES DE TIEMPO CON TSVIZ
https://github.com/xtreamsrl/tsviz
https://www.youtube.com/watch?v=t8PZbP5b8EM&t=1870s
```{r}
#install.packages("tsviz")

#library(tsviz)

#p <- tsviz::crypto_prices

#tsviz::tsviz()
```



```{r}
#los coches con motor más grande consumen mas combustible
#que los coches con motor más pequeño?
#La relación consumo/tamaño es lineal? Es no lineal?
#Es positiva? Es negativa?


#PLANTILLA PARA HACER UNA REPRESENTACION GRAFICA CON GGPLOT
#ggplot(data=<DATA_FRAME>) +
#  <GEOM_FUNCTION>(mapping= aes(<MAPPINGS>))

#displ: tamaño del motor del coche en litros
#hwy: número de millas de  autopista por galón de combustible (3.78541 litros)

#tamaño del motor "displ" vs número de millas de  autopista por galón de combustible "hwy"
ggplot(data=mpg) +
  geom_point(mapping=aes(x=displ,y=hwy))
```


```{r}
#número de cilindros "cyl" vs número de millas de  autopista por galón de combustible "hwy"
ggplot(data=mpg) +
  geom_point(mapping=aes(x=cyl,y=hwy))
```


```{r}
#número de cilindros "cyl" vs número de millas en ciudad por galón "cty"
ggplot(data=mpg) +
  geom_point(mapping=aes(x=cyl,y=cty))
```

```{r}
#tipo de coche "class" vs tipo de tren de manejo "drv"
ggplot(data=mpg) +
  geom_point(mapping=aes(x=class,y=drv))
```

```{r}
#tamaño del motor "displ" vs número de millas de  autopista por galón de combustible "hwy"
ggplot(data=mpg) +
  geom_point(mapping=aes(x=displ,y=hwy))
```

```{r}
#representando 3 variables:

#haciendo un grafico , representando una tercera variable tipo clase por color en el scater plot:
ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ,y=hwy, color=class))
```

```{r}
#haciendo un grafico , representando una tercera variable tipo clase por tamaño en el scater plot:
ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ,y=hwy, size=class))
```

```{r}
#haciendo un grafico , representando una tercera variable tipo clase por transparencia en el scater plot:
ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ,y=hwy, alpha=class))
```

```{r}
#haciendo un grafico , representando una tercera variable tipo clase por la forma en el scater plot:
ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ,y=hwy, shape=class))
```

```{r}
#eleccion manual de esteticas, va por separado luego de una coma
ggplot(data=mpg) +
  geom_point(mapping=aes(x=displ,y=hwy), color="red")
```
```{r}
#pintar todo de verde
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy), color = "green")
```
```{r}
#plantilla de formas:
d=data.frame(p=c(0:25))
ggplot() +
  scale_y_continuous(name="") +
  scale_x_continuous(name="") +
  scale_shape_identity() +
  geom_point(data=d, mapping=aes(x=p%%16, y=p%/%16, shape=p), size=5, fill="yellow") +
  geom_text(data=d, mapping=aes(x=p%%16, y=p%/%16+0.25, label=p), size=3)
```

```{r}
#eleccion manual de esteticas, va por separado luego de una coma mas detallada
ggplot(data=mpg) +
  geom_point(mapping=aes(x=displ,y=hwy), shape=23,size=10,color="red",fill="yellow")
```


```{r}
#para graficar separando por colores los que cumplen un requisito
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color=displ <4))
```

```{r}
##FACETS
# facet_wrap(~<FORMULA_VARIABLE>): la variable debe ser discreta
ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ,y=hwy))+
  facet_wrap(~class,nrow=3)
```

```{r}
# facet_grid(<FORMULA_VARIABLE1>~<FORMULA_VARIABLE2>)
ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ,y=hwy))+
  facet_grid(drv~cyl)
```

```{r}
#este metodo seria equivalente al facet_wrap, reemplazando una variable por "."
ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ,y=hwy))+
  facet_grid(.~cyl)
```

```{r}
#dibujando una linea suavizada para ver correlacion
ggplot(data=mpg)+
  geom_smooth(mapping = aes(x=displ,y=hwy))
```

```{r}
#se agrega tipo de linea en una tercera variable
ggplot(data=mpg)+
  geom_smooth(mapping=aes(x=displ,y=hwy,linetype=drv))
```


```{r}
#se agrega tipo de linea en una tercera variable
ggplot(data=mpg)+
  geom_smooth(mapping=aes(x=displ,y=hwy,linetype=drv,color=drv))
```

```{r}
#combinando dos graficos
ggplot(data=mpg)+
  geom_point(mapping = aes(x=displ,y=hwy,linetype=drv,color=drv))+
  geom_smooth(mapping=aes(x=displ,y=hwy,linetype=drv,color=drv))
```


```{r}
#probando con group
ggplot(data=mpg)+
  geom_smooth(mapping = aes(x=displ,y=hwy,group=drv,color=drv),
              show.legend = T)
```


```{r}
#en vez de escribir graficos combinados asi:
ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ,y=hwy))+
  geom_smooth(mapping = aes(x=displ,y=hwy))
```


```{r}
#tambien se pueden hacer asi:
ggplot(data=mpg,mapping=aes(x=displ,y=hwy))+
  geom_point()+
  geom_smooth()

```


```{r}
#otro ejemplo
ggplot(data=mpg,mapping=aes(x=displ,y=hwy))+
  geom_point(mapping=aes(shape=class))+
  geom_smooth(mapping = aes(color=drv))
```

```{r}
#otro ejemplo, mostrando curva solo para un tipo de coche, 
#ademas eliminando el intervalo de confianza de la curva
ggplot(data=mpg,mapping=aes(x=displ,y=hwy))+
  geom_point(mapping=aes(color=class))+
  geom_smooth(data=filter(mpg,class=="suv"),se=F)
```


```{r}
#otro ejemplo
ggplot(data = mpg, mapping = aes(x=displ, y = hwy,color = drv)) + 
  geom_point() + 
  geom_smooth( se = F)
```

```{r}
#tarea1
ggplot(data = mpg, mapping = aes(x=displ, y = hwy)) + 
  geom_point() + 
  geom_smooth( se = F)
```


```{r}
#tarea2
ggplot(data = mpg, mapping = aes(x=displ, y = hwy, group=drv)) + 
  geom_point() + 
  geom_smooth( se = F)
```

```{r}
#tarea3
ggplot(data = mpg, mapping = aes(x=displ, y = hwy, color=drv)) + 
  geom_point() + 
  geom_smooth( se = F)
```

```{r}
#tarea4
ggplot(data = mpg, mapping = aes(x=displ, y = hwy)) + 
  geom_point(aes(color=drv)) + 
  geom_smooth( se = F)
```


```{r}
#tarea5
ggplot(data = mpg, mapping = aes(x=displ, y = hwy) ) + 
  geom_point(mapping = aes(col=drv, shape = drv)) + 
  geom_smooth(mapping = aes(linetype = drv), se=F)
```
```{r}
#tarea6
ggplot(data = mpg, mapping = aes(x=displ, y = hwy) ) + 
  geom_point(mapping = aes(fill = drv), size = 4, 
             shape = 23, col = "white", stroke = 2) 
```
```{r}
#DATA SET DIAMONDS
data(diamonds)
```

```{r}
#DIAGRAMA DE BARRAS a partir de datos transaccionales
ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=cut))
```

```{r}
#se obtiene el mismo diagrama de barras con este otro metodo
ggplot(data=diamonds)+
  stat_count(mapping = aes(x=cut))
```

```{r}
#generando barras a partir de datos transaccionales pero en porcentajes
ggplot(data=diamonds)+
  geom_bar(mapping=aes(x=cut,y=..prop..,group=1))

```

```{r}

#basae con ponderaciones
demo_diamonds<-tribble(
  ~cut, ~freqs,
  "Fair", 1610,
  "Good", 4906,
  "Very Good", 12082,
  "Premium", 13791,
  "Ideal", 21551
)
```

```{r}
#generando barras a partir de datos ponderados
ggplot(data=demo_diamonds)+
  geom_bar(mapping = aes(x=cut,y=freqs),stat="identity")
```
```{r}
#sin embargo es mejor usar geom_col cuando ya existe la variable ponderada,...
#...se obtendra el mismo resultado que usando la funcion"identity" en geom_bar

#tarea diferencia entre bar y col
ggplot(data=demo_diamonds)+
  geom_col(mapping=aes(x=cut,y=freqs))
```
```{r}
#para graficar maxims minimos y mediana
ggplot(data = diamonds)+
  stat_summary(
    mapping = aes(x=cut,y=depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y=median,
  )
```

```{r}
#colores y formas de los graficos

#cambiando de color los bordes
ggplot(data=diamonds) +
  geom_bar(mapping = aes(x=cut,colour=cut))
```
```{r}
#cambiando el color de relleno
ggplot(data=diamonds) +
  geom_bar(mapping = aes(x=cut,fill=cut))
```

```{r}
#aprovechando el fill para visualizar una tercera variable.
ggplot(data = diamonds)+
  geom_bar(mapping = aes(x=cut,fill=clarity))
```

```{r}
#formas de comparar diagramas de barras

##position="identity"
ggplot(data = diamonds, mapping=aes(x=cut,fill=clarity))+
  geom_bar(alpha=0.2,position = "identity")
```
```{r}
ggplot(data = diamonds, mapping=aes(x=cut,color=clarity))+
  geom_bar(fill=NA,position = "identity")
```

```{r}
##position="fill", permite comprar porcentajes
ggplot(data=diamonds,mapping = aes(x=cut,fill=clarity))+
  geom_bar(position="fill")
```
```{r}
##position="dodge"
ggplot(data=diamonds,mapping = aes(x=cut,fill=clarity))+
  geom_bar(position="dodge")
```
```{r}
#volvemos al scatterplot
##positio="jitter" para que los puntos no se superpongan
ggplot(data = mpg, mapping=aes(x=displ,y=hwy))+
  geom_point(position="jitter")
```
```{r}
#?position_stack
##sistemas de coordenadas
ggplot(data=mpg,mapping=aes(x=class,y=hwy))+
  geom_boxplot()
```
```{r}
#para girar se usa coord_flip()
ggplot(data=mpg,mapping=aes(x=class,y=hwy))+
  geom_boxplot()+
  coord_flip()

```

```{r}
#para ver mapas

#cargamos datos de mapas
#coord_quickmap() ->configura el aspect ratio para mapas
#install.packages("maps")
#library(maps)

#usamos la funcion para ver mapas con longitud y latitud
usa<-map_data("usa")
```


```{r}
#sin coordinate
ggplot(usa,aes(long,lat,group=group))+
  geom_polygon(fill="blue",color="white")
```

```{r}
#con coordinate quickmap mejora el aspect ratio
ggplot(usa,aes(long,lat,group=group))+
  geom_polygon(fill="blue",color="white")+
  coord_quickmap()
```
```{r}
italy<-map_data("italy")
ggplot(data=italy,aes(long,lat,group=group))+
  geom_polygon(fill="blue",color="white")+
  coord_quickmap()
```

```{r}
#coord_polar
ggplot(data=diamonds)+
  geom_bar(
    mapping=aes(x=cut,fill=cut),
    show.legend = F,
    width = 1
  )+
  theme(aspect.ratio=1)+ #hace que el grafico este cuadrado
  labs(x=NULL,y=NULL)+ #quita los nombres de los ejes
  coord_polar() #convierte el grafico en radial
```

```{r}
ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=clarity,y=..prop..,group=1))
```
```{r}
#ejemplo final combinando parametros
ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=clarity,fill=clarity,y=..count..))+
  coord_polar()+
  facet_wrap(~cut)+
  labs(x=NULL,y=NULL,title="Ejemplo final de ggplot con JB",
       caption = "hola",
       subtitle = "probando")
```
```{r}
ggplot(data = mpg, mapping = aes(x = cty, y = hwy )) + 
  geom_point()+
  geom_smooth()+
  geom_jitter()
```

```{r}
ggplot(data = mpg, mapping = aes(x = cty, y = hwy )) + 
  geom_point()+
  geom_smooth()+
  geom_count()

```
```{r}
#este grafico
ggplot(data=mpg,mapping=aes(x=class,y=hwy))+
  geom_boxplot(position="dodge")+
  coord_flip()
```
```{r}
#da el mismo resultdo que este
ggplot(data=mpg,mapping=aes(x=class,y=hwy))+
  geom_boxplot()+
  coord_flip()
```

```{r}
#diagrama de barras apilado en polar

##position="identity"
ggplot(data = diamonds, mapping=aes(x=cut,fill=clarity))+
  geom_bar(alpha=0.2,position = "identity")+
  coord_polar()
```

```{r}
ggplot(data = mpg, mapping = aes(x = cty, y = hwy )) + 
  geom_point() + 
  geom_abline() + 
  coord_fixed()
```

